name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, windows-2022, macos-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install .[dev]

    - name: Check Syntax Errors with compileall
      run: |
        python -m compileall src

    - name: Run Linter (pylint)
      run: |
        pylint src/msftoolbox

    - name: Run Tests with pytest and Coverage
      run: |
        pytest src/tests --cov=src/msftoolbox --cov-report=xml
